### ISSUE TITLE
login & logout backend

### ISSUE THREAD

**Issue by bni0922** [BenYoo-ben/LightFileExplorer#5]
How to register / login / logout an account (use POSTMAN)

register
http://localhost:5000/api/users/register
post { id : "id", password: "password"}

login
http://localhost:5000/api/users/login
post { id : "id", password: "password"}

logout
http://localhost:5000/api/users/logout
get { id : "id", password: "password"}

**Comment by BenYoo-ben** [comment]
Won't do for a while.
